spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  upload:
    src: E:\aiyoImg
  datasource:
    username: mysql
    password: 1qw23er4
    url: jdbc:mysql://129.211.1.185:3306/apiyoo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.apiyoo.anthorization.swy.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 关闭MP3.0自带的banner
    banner: false

  #showSql
  logging:
    level:
      com:
        example:
          mapper: debug